### ISSUE TITLE
Grammar Issues

### ISSUE THREAD

**Issue by Ashley-Westcott** [learn-co-curriculum/a-react-app-example#6]
When you open up the server it reads:

In React apps, we write JSX - it looks like HTML, and uses a lot HTML syntax. JSX lets us include JavaScript functions right along with the HTML, and also allows us to add in components, which are separate, self-contained chunks of of JSX.

- "uses a lot HTML syntax" -> change to "uses a lot of HTML syntax"
- "self-contained chunks of of JSX." -> remove one of the "of's"

**Comment by maxwellbenton** [comment]
Hi @Ashley-Westcott,

Thanks for catching these and providing feedback. We've updated the text in both the app and the readme with these fixes.

Thank you for contributing to a Learn lesson!
